export interface AudienceMemberUI {
   birthDate: string,
   city: string,
   email: string,
   firstName: string,
   gender: string,
   id: number,
   landingLink: string,
   lastName: string,
   launchGroup: string,
   mbiId: string,
   mobileNumber: string,
   organization: string,
   pcpClinicGroup: string,
   pcpFirstName: string,
   pcpLastName: string,
   pcpNpi: string,
   personId: number,
   primaryLanguage: string,
   provider: string,
   state: string,
   streetAddress: string,
   zipCode: string,
}