export interface AudienceMemberDB {
   birth_date: string,
   city: string,
   email: string,
   first_name: string,
   gender: string,
   landing_link: string,
   last_name: string,
   launch_group: string,
   mbi_id: string,
   mobile_number: string,
   organization_name: string,
   pcp_clinic_group: string,
   pcp_first_name: string,
   pcp_last_name: string,
   pcp_npi: string,
   primary_language: string,
   provider_name: string,
   recruitment_id: number,
   spp_person_id: number,
   state: string,
   street_address: string,
   zip_code: string,
}