export interface EmailDB {
   deleted_datetime_utc: string,
   email_message: string,
   email_message_html: string,
   email_subject: string,
   mode_tag_desc: string,
   mode_tag_name: string,
   recipient_clicked_datetime_utc: string,
   recipient_email: string,
   ref_mode_email_id: number,
   ref_mode_tag_id: number,
   sb_intervention_email_id: number,
   sb_intervention_guid: string,
   scheduled_datetime_utc: string,
   sender_email: string,
   sender_ref_user_id: number,
   sent_datetime_utc: string,
   spp_person_id: number,
   switchboard_aiml_algorithm_id: number,
}