export interface EmailUI {
   aimlId: number,
   clickedOn: string,
   deletedOn: string,
   emailTemplateId: number,
   guid: string,
   htmlMessage: string,
   id: number,
   message: string,
   messageTagId: number,
   personId: number,
   recipientEmail: string,
   sendFrom: number,
   sendOn: string,
   senderEmail: string,
   sentOn: string,
   subject: string,
   tagDescription: string,
   tagName: string,
}