export interface InAppMessageUI {
   aimlId: number,
   appId: number,
   clickedOn: string,
   createdBy: number,
   createdOn: string,
   deletedOn: string,
   guid: string,
   id: number,
   inAppMessageTemplateId: number,
   modifiedBy: number,
   modifiedOn: string,
   personId: number,
   recipientAppId: number,
   sendFrom: number,
   sendOn: string,
   sendTo: number,
   sentOn: string,
}