export interface UserDemographicUI {
   createdBy: number,
   createdByName: string,
   createdOn: string,
   demographicId: number,
   description: string,
   disabledOn: string | null,
   format: null,
   id: number,
   isDisabled: boolean,
   isRequired: boolean,
   label: string,
   length: number,
   modifiedBy: number,
   modifiedByName: string,
   modifiedOn: string,
   name: string,
   type: string,
   userId: number,
   value: string,
}