export interface UserDemographicDB {
   data_format: null,
   data_length: number,
   data_type: string,
   demographic_desc: string,
   demographic_label: string,
   demographic_name: string,
   demographic_value: string,
   disabled_datetime_utc: string | null,
   disabled_flag: boolean,
   ref_demographic_id: number,
   ref_user_id: number,
   required_field_flag: boolean,
   row_created_by_user_name: string,
   row_created_datetime_utc: string,
   row_created_user_id: number,
   row_modified_by_user_name: string,
   row_modified_datetime_utc: string,
   row_modified_user_id: number,
   user_demographic_id: number,
}